"""first tables

Revision ID: 4f93a15d2cff
Revises: 
Create Date: 2024-03-24 11:40:32.472456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f93a15d2cff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipality',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('region_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('municipality_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('municipality')
    op.drop_table('region')
    # ### end Alembic commands ###
