"""add score table

Revision ID: 9d4ead4c3df4
Revises: e153732a24f0
Create Date: 2024-03-29 16:39:55.191397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4ead4c3df4'
down_revision: Union[str, None] = 'e153732a24f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('dzi_id', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Double(), nullable=True),
    sa.Column('grade', sa.Double(), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('quantity_people', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dzi_id'], ['dzi.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###
